---
- include_vars: casks.yml
- file: path={{ ansible_env.HOME }}/Applications state=directory
# - homebrew: name=caskroom/cask/brew-cask state=upgraded
- command: brew install caskroom/cask/brew-cask
- homebrew_cask: name={{ item }} state=installed
  with_items: casks
- command: defaults write {{ item }}
  with_items:
    - com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
