---
- include_vars: casks.yml
# - homebrew: name=caskroom/cask/brew-cask state=upgraded
- command: brew install caskroom/cask/brew-cask
- homebrew_cask: name={{ item }} state=installed
  with_items: casks
