---
- include_vars: casks.yml

- file: path={{ ansible_env.HOME }}/Applications state=directory

# - homebrew: name=caskroom/cask/brew-cask state=upgraded
- homebrew_tap: name=caskroom/cask state=present
- homebrew: name=brew-cask state=present

- homebrew_cask: name={{ item }} state=installed
  with_items: casks

- synchronize:
    src: "{{ item }}"
    dest: "{{ item | regex_replace(' ', '\ ') }}"
    rsync_opts: --ignore-existing
  with_items: prefs
