---
- include_vars: defaults.yml

- osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: osx_defaults
  notify: restart osx system services
