---
- include_vars: defaults.yml
- command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1
  sudo: True
- command: defaults write {{ item }}
  with_items: defaults | list
- command: killall {{ item }}
  with_items:
    - Finder
    - Dock
    - SystemUIServer
- command: open ~/.dotfiles/Alpha.terminal
