---
- homebrew: name=dockutil state=present
- command: /usr/local/bin/dockutil --list
  register: dockutil_result
- command: /usr/local/bin/dockutil --remove all
  when: not (dockutil_result.stdout_lines | length == 1 and dockutil_result.stdout | search("^Downloads"))
- command: /usr/local/bin/dockutil --add ~/Downloads
                                      --view list
                                      --display stack
                                      --sort datemodified
  when: not (dockutil_result.stdout_lines | length == 1 and dockutil_result.stdout | search("^Downloads"))
- homebrew: name=dockutil state=absent
