---
- homebrew: name=dockutil state=present
- command: /usr/local/bin/dockutil --remove all
- command: /usr/local/bin/dockutil --add ~/Downloads --view list
                                      --display stack
                                      --sort datemodified
- homebrew: name=dockutil state=absent
