# https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-repository

- hosts: attitude-adjuster
  vars_files:
    - vars.yml.private
  become: yes
  tasks:

    - name: install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - gnupg2

    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    # https://github.com/moby/moby/issues/31405#issuecomment-501494874
    - name: add docker apt repository
      apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
        state: present
        filename: docker

    - name: install docker
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: add myself to docker group
      user:
        name: alpha
        groups: docker
        append: yes

    - name: install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-compose
        - python-docker

