- hosts: attitude-adjuster
  become: yes
  tasks:

    - name: install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim

- import_playbook: security.yml

- import_playbook: ddclient.yml
- import_playbook: home-assistant.yml
- import_playbook: docker.yml
