- name: install homebrew-bundle
  command: brew tap Homebrew/bundle

# Not sure if this is needed anymore - was used for installing casks
- name: authenticate sudo
  ping:
  become: yes

- name: homebrew-bundle install
  command: brew bundle
  args:
    chdir: ~/.dotfiles
