- hosts: local
  tasks:
    - name: Run brew bundle
      ansible.builtin.command: brew bunfle --file=~/.dotfiles/personal/Brewfile

- hosts: local
  tags: library
  tasks:

    - name: Create KeyBindings dir
      ansible.builtin.file:
        path: ~/Library/Application Support/MailMate/Resources/KeyBindings
        state: directory
        mode: "0755"

    - name: Symlink key bindings
      ansible.builtin.file:
        src: ~/.dotfiles/macos/MailMate.plist
        dest: ~/Library/Application Support/MailMate/Resources/KeyBindings/Alpha.plist
        state: link

# vim: ft=yaml.ansible
