- hosts: all
  tasks:
  - name: install rustup
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    args:
      warn: False

  - name: install rustfmt, clippy
    command: rustup component add {{ item }}
    with_items:
    - rustfmt
    - clippy
