#!/bin/sh

# Overrides for --exclude and --languages can be put into .ctags.d/*.ctags

set -e
PATH="/opt/homebrew/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | ctags --tag-relative -L - -f"$$.tags"
mv "$$.tags" "tags"
