---
formulae:
  - chruby
  - ctags
  - fasd
  - git
  # - macvim # Needs install_options=override-system-vim
  - ruby-install
  - reattach-to-user-namespace
  - the_silver_searcher
  - tmux
  - youtube-dl
  - zsh
casks:
  - adium
  - alfred
  - black-ink
  - dropbox
  - google-chrome
  - fantastical
  - firefox
  - flux
  - moom
  - onepassword
  - plug
  - qlmarkdown
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - steam
  - things
  - vlc
  - ynab
fonts:
  - font-sauce-code-powerline
