---
- file: path={{ item }} state=directory # TODO Do this automatically
  with_items:
    - ~/.bundle
    - ~/.ssh
    - ~/.vim_tmp
- file: src=~/.dotfiles/{{ item.key }} dest={{ item.value }} state=link
  with_dict: dotfiles
- file:
    src: ~/Dropbox/dotfiles/{{ item.key }}
    dest: "{{ item.value }}"
    state: link
    force: yes # Since these won't exist until later.
  with_dict: private
- file: src={{ item }} dest=~/.ssh/{{ item | basename }} state=link
  with_fileglob: ~/.dotfiles/.ssh/*
