# TODO
# - Only run on OS X?
# - Better reloading of dnsmasq after re-configuring
- hosts: all
  tasks:
  - homebrew: name=dnsmasq state=present
  - file: src=~/.dotfiles/dnsmasq/dnsmasq.conf dest=/usr/local/etc/dnsmasq.conf state=link
  - shell: cp -fv /usr/local/opt/dnsmasq/*.plist /Library/LaunchDaemons
    become: yes
  - file: path=/Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist owner=root
    become: yes
  - file: path=/usr/local/etc/dnsmasq.d state=directory
  - get_url:
      url: http://pgl.yoyo.org/adservers/serverlist.php?hostformat=dnsmasq&showintro=0&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=&mimetype=plaintext
      dest: /usr/local/etc/dnsmasq.d/adblock.conf
  - command: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    become: yes
  - command: launchctl stop /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    become: yes
    ignore_errors: True
  - command: launchctl start /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    become: yes
    ignore_errors: True
