- name: install Python
  homebrew: name=python state=present

- name: install Powerline
  command: >
    /usr/local/bin/pip
      install
      --user
      --editable={{ ansible_env.HOME }}/.dotfiles/src/powerline

- name: symlink Powerline configs
  file: src={{ item }} dest=/usr/local/bin/{{ item | basename }} state=link
  with_fileglob: ~/.dotfiles/src/powerline/scripts/*
