- name: check if Powerline is already installed
  shell: pip list | grep Powerline
  ignore_errors: true
  register: powerline_installed

- name: install Powerline
  command: >
    pip
      install
      --user
      --editable=~/.dotfiles/src/powerline
  when: powerline_installed.failed

- name: symlink Powerline configs
  file: src={{ item }} dest=/usr/local/bin/{{ item | basename }} state=link
  with_fileglob: ~/.dotfiles/src/powerline/scripts/*
