- hosts: all
  tasks:
  - name: symlink dotfiles
    file: src={{ ansible_env.HOME }}/Dropbox/dotfiles dest={{ ansible_env.HOME}}/.dotfiles state=link
- include: config.yml
- hosts: all
  tasks:
  - name: set zsh as default shell
    user: name=alpha shell=zsh
    sudo: yes
  - name: symlink zprezto
    file: src={{ ansible_env.HOME }}/Dropbox/dotfiles/src/prezto dest={{ ansible_env.HOME}}/.zprezto state=link
  - name: symlink zsh runcoms
    file: src={{ ansible_env.HOME }}/Dropbox/dotfiles/src/prezto/runcoms/{{ item }} dest={{ ansible_env.HOME}}/.{{ item }} state=link
    with_items:
      - zlogin
      - zlogout
      - zpreztorc
      - zprofile
      - zshenv
      - zshrc
  - name: setup ssh keys
    local_action: command ruby ~/.dotfiles/scripts/setup_ssh_keys.rb
    when: ansible_domain == "local"
