---
- hosts: ramble-hard
  tasks:

  - name: add ssh keys
    authorized_key:
      user: root
      key: https://github.com/kejadlen.keys

- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/lets_encrypt/main.yml
- import_playbook: playbooks/babybuddy/main.yml
- import_playbook: playbooks/pixelfed/install.yml
