"$schema" = "https://jj-vcs.github.io/jj/prerelease/config-schema.json"

[user]
name = "Alpha Chen"
email = "alpha@kejadlen.dev"

# https://discord.com/channels/968932220549103686/968932220549103689/1324858422910255155
[merge-tools.gitpatch]
program = "sh"
edit-args = ["-c", '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  git -C "$right" add --intent-to-add -A
  git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" restore . # undo changes in modified files
  git -C "$right" reset .   # undo --intent-to-add
  git -C "$right" clean -q -df # remove untracked files
''',
]
merge-args = ["-c", "echo gitpatch cannot be used as a diff tool"]
diff-args = ["-c", "echo gitpatch cannot be used as a diff tool"]

# https://github.com/bryceberger/config/commit/9a3185b6b3a7a81246f84325448e878a5a8281f4
[merge-tools.git-pkgs]
program = "git-pkgs"
diff-args = ["diff-file", "--color=always", "$left", "$right"]
diff-invocation-mode = "file-by-file"
edit-args = []

[diff.color-words]
max-inline-alternation = 0

[colors]
"diff modified" = "blue"
"diff token" = { underline = false }

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINCttH8nEfk1uZ2291P4mbCoNcHxnr9iNBlbZckykeZ8"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[git]
sign-on-push = true
private-commits = "private() | wip()"
write-change-id-header = true
track-default-bookmark-on-clone = false

[templates]
# show diff when committing
draft_commit_description = '''
  separate(
    "\n",
    builtin_draft_commit_description,
    "JJ: ignore-rest",
    diff.git(),
  )
'''
# show an empty diamond when unpushed
log_node = '''
  if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
    "◇",
    builtin_log_node
  )
'''

[template-aliases]
'in_branch(commit)' = 'commit.contained_in("immutable_heads()..bookmarks()")'

[ui]
default-command = "st"
diff-editor = "gitpatch"
# diff-editor = ",jj-nvimdiff"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
pager = ":builtin"

# default will be `glob:` in the future, so switch to it proactively
# and remove this once it actually becomes the default
revsets-use-glob-by-default = true

[ui.movement]
edit = true

[revset-aliases]
'immutable_heads()' = 'builtin_immutable_heads() | heads(~mine())'

'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_merge()' = 'closest_merge(@)'
'closest_merge(to)' = 'heads(::to & merges())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

'user(x)' = 'author(x) | committer(x)'

'wip()' = 'description("wip:*")'
'private()' = 'description("private:*")'

[aliases]
accuse = ["file", "annotate"]
jj = []
tug = ["util", "exec", "--", "bash", "-c", """
  ref=${1:-@}
  jj bookmark move --from "closest_bookmark($ref)" --to "closest_pushable($ref)"
""", ""]
stack = [
  "rebase",
  "--insert-after", "trunk()",
  "--insert-before", "heads(closest_merge(@) | mm)",
  "--revisions"
]
pr = ["util", "exec", "--", "bash", "-c", """
  gh pr create --head \
    $(jj log -r 'closest_bookmark(@)' -T 'bookmarks' --no-graph | cut -d ' ' -f 1)
"""]
pull = ["util", "exec", "--", "bash", "-c", """
  jj git fetch
  jj rebase --branch "visible_heads() & mutable()" --destination "trunk()"
  jj simplify-parents
"""]

# https://github.com/jj-vcs/jj/discussions/3549
# [experimental-advance-branches]
# enabled-branches = ["glob:*"]
# disabled-branches = ["main", "mm"]

[fix.tools.ruff-format]
command = ["ruff", "format", "--stdin-filename", "$path", "-"]
patterns = ["'**/*.py'"]

[fix.tools.ruff-check]
command = ["ruff", "check", "--fix", "--stdin-filename", "$path", "-"]
patterns = ["'**/*.py'"]

[fix.tools.cargo-fmt]
command = ["rustfmt"]
patterns = ["'**/*.rs'"]
